using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Beyond8.Catalog.Domain.Enums;
using Beyond8.Common.Data.Base;
using NpgsqlTypes;

namespace Beyond8.Catalog.Domain.Entities
{
    public class Course : BaseEntity
    {
        // Full-text search vector (auto-generated by database trigger)
        public NpgsqlTsVector? SearchVector { get; set; }

        public Guid InstructorId { get; set; }
        [MaxLength(100)]
        public string InstructorName { get; set; } = string.Empty;
        public virtual InstructorVerificationStatus InstructorVerificationStatus { get; set; } = InstructorVerificationStatus.Verified;

        public Guid CategoryId { get; set; }
        [ForeignKey(nameof(CategoryId))]
        public virtual Category Category { get; set; } = null!;

        // Basic Info
        [Required, MaxLength(200)]
        public string Title { get; set; } = string.Empty;

        [Required, MaxLength(220)]
        public string Slug { get; set; } = string.Empty;

        [Required]
        public string Description { get; set; } = string.Empty;

        [MaxLength(1000)]
        public string? ShortDescription { get; set; }

        // Pricing
        [Column(TypeName = "decimal(18, 2)")]
        public decimal Price { get; set; } = 0;

        // Status & Visibility
        public CourseStatus Status { get; set; } = CourseStatus.Draft;
        public CourseLevel Level { get; set; } = CourseLevel.Beginner;

        [MaxLength(10)]
        public string Language { get; set; } = "vi-VN";

        // Media
        [Required]
        public string ThumbnailUrl { get; set; } = string.Empty;

        // Learning Outcomes (JSONB)
        [Column(TypeName = "jsonb")]
        public string Outcomes { get; set; } = "[]";  // ["outcome 1", "outcome 2"]

        [Column(TypeName = "jsonb")]
        public string? Requirements { get; set; }  // ["requirement 1"]

        [Column(TypeName = "jsonb")]
        public string? TargetAudience { get; set; }  // ["student type 1"]

        // Statistics
        public int TotalStudents { get; set; } = 0;
        public int TotalSections { get; set; } = 0;
        public int TotalLessons { get; set; } = 0;
        public int TotalDurationMinutes { get; set; } = 0;

        [Column(TypeName = "decimal(3, 2)")]
        public decimal? AvgRating { get; set; }

        public int TotalReviews { get; set; } = 0;
        public int TotalRatings { get; set; } = 0;

        public Guid? ApprovedBy { get; set; }
        public DateTime? ApprovedAt { get; set; }

        [MaxLength(1000)]
        public string? ApprovalNotes { get; set; }

        [MaxLength(1000)]
        public string? RejectionReason { get; set; }

        public bool IsActive { get; set; } = true;

        // Relationships
        public virtual ICollection<Section> Sections { get; set; } = [];
        public virtual ICollection<CourseDocument> Documents { get; set; } = [];
    }
}
